"""empty message

Revision ID: 1feb4dd109bc
Revises: f410772eea47
Create Date: 2023-09-24 05:36:29.395246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1feb4dd109bc'
down_revision = 'f410772eea47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('middle_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=150), nullable=False))

    # ### end Alembic commands ###
